<section id="content">    
    <ul class="column">

        <div class="naoEncontrado">PEDIDO FINALIZADO COM SUCESSO!<br> 
            CÓDIGO DO PEDIDO: <?= $this->codigoPedido ?>
        </div>
        <table class="tabelaFormasPagamento">
            <tr>
                <td colspan="2" class="center">
                    <a href="<?= $this->baseUrl() ?>/vitrine">Voltar para Vitrine</a>
                </td>
            </tr>
        </table>
    </ul>
</section>



